import {createSlice} from '@reduxjs/toolkit';

const initialState = {
  value: 0,
};

export const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    increment: state => {
      // Redux Toolkit allows "mutating" the state because it uses Immer,
      // which detects changes and returns a new immutable state.
      state.value += 1;
    },
    decrement: state => {
      state.value -= 1;
    },
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const {increment, decrement, incrementByAmount} = counterSlice.actions;

// Export the reducer
export default counterSlice.reducer;
